### PR TITLE
Don't lower account name before calling accounts_get_account

### LINKED ISSUE #725: Case-sensitive account names don't work
Hi,

I have an issue using account names with a capital character at the beginning, e.g., Me.
For example:

This does NOT work:
/account add Me
/account set Me jid <JID>
/connect Me

But this does work:
/account add me
/account set me jid <JID>
/connect me

My system is an Arch Linux with profanity 0.4.7 from the repos.

Greetings!

### PR DESCRIPTION
**Pull request by philipflohr**
This fixes #725

### CODE REVIEW

**Comment by jubalh** [comment]
@philipflohr cool, thanks.
Can you run `make  check-TESTS` and take a look at the unit tests?

File: tests/unittests/test_cmd_connect.c [hunk 1]
```diff
@@ -89,29 +89,49 @@ void cmd_connect_fail_message(void **state)
     assert_true(result);
 }
 
-void cmd_connect_lowercases_argument(void **state)
+void cmd_connect_lowercases_argument_with_no_account(void **state)
 {
-    gchar *args[] = { "USER@server.ORG", NULL };
+    gchar *args[] = { "USER@server.org", NULL };
```
Comment (jubalh) [inline tests/unittests/test_cmd_connect.c]: why the org in lowercase?

**Comment by jubalh** [comment]
Thanks for the contribution @philipflohr !
