### PR TITLE
Ensure MUC is Non-Anonymous before starting OMEMO

### LINKED ISSUE #1065: OMEMO start on unsupported MUC
It is possible to start OMEMO on a MUC which isn't NON ANONYMOUS.
Doing so will result in either a segfault or message being sent encrypted with no key on it.

### PR DESCRIPTION
**Pull request by paulfariello**
Store MUC anonymous type in mucwin for that purpose.

Fixes #1065

### CODE REVIEW

**Comment by jubalh** [comment]
Looking good. Waiting for build to pass before merging.

File: src/command/cmd_funcs.c [hunk 1]
```diff
@@ -8031,14 +8031,14 @@ cmd_omemo_start(ProfWin *window, const char *const command, gchar **args)
...
-            /* TODO: Check room is configured correctly, no anonymous and access to
-             * full jid */
-            omemo_start_muc_sessions(mucwin->roomjid);
-
-            mucwin->is_omemo = TRUE;
+            if (muc_anonymity_type(mucwin->roomjid) == MUC_ANONYMITY_TYPE_NONANONYMOUS) {
+                omemo_start_muc_sessions(mucwin->roomjid);
+                mucwin->is_omemo = TRUE;
+            } else {
+                win_println(window, THEME_DEFAULT, '!', "MUC must non-anonymous (i.e. be configured to present real jid to anyone) in order to support OMEMO.");
```
Comment (jubalh) [inline src/command/cmd_funcs.c]: sorry one small thing still:) MUC must **be**

**Comment by jubalh** [comment]
Thanks!
